name: multistep_task_educational_system
description: Flutter Web education system created for solving multistep multivariant tasks
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # Annotations
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

  # Routing
  auto_route: ^5.0.4
  url_launcher: ^6.1.10

  # Dependency Injection
  get_it: ^7.2.0
  injectable: ^2.1.0

  # Bloc
  flutter_bloc: ^8.1.2
  bloc_concurrency: ^0.2.1

  # Core packages
  dartz: ^0.10.1
  intl: ^0.17.0
  path: ^1.8.2
  path_provider: ^2.0.12


  permission_handler: ^10.2.0

  # Local storage
  shared_preferences: ^2.0.17

  # DB
  drift: ^2.5.0

  # UI
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.4.0
  cached_network_image: ^3.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  auto_route_generator: ^5.0.3
  injectable_generator: ^2.1.3
  chopper_generator: ^6.0.0
  drift_dev: ^2.5.1
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
